### ISSUE TITLE
Issue in FOxpro2Python

### ISSUE THREAD

**Issue by Act1234** [mwisslead/foxpro2python#2]
Hi

As i downloaded the zip file and extracted in my local.  As per instruction i installed python27 under this directory (Foxpro2Python).  Then when i ran the tests.prg, the vfp screen got closed.  As i verified the issue, the foxpro got closed when it execute py_initialize() method.  

Can you help me how to solve this problem.  I am using windows 10.

**Comment by mwisslead** [comment]
I believe this may be a bug due to deallocation of the python home string memory. I have a fix in the python3 branch I will backport to the master branch shortly.

**Comment by Act1234** [comment]
can the updated python 3 will work in foxpro 9 32 bit system.  if so, please provide the same to me , so that i can start test.

**Comment by mwisslead** [comment]
I decided to just merge the new python3 support into master which should fix your particular issue.

You should be able to use it exactly as you have been. It supports python2 and python3. In either case you must use the 32 bit version of python if your foxpro runtime is 32bit.

**Comment by Act1234** [comment]
can i know the python version.  So that i can download and install

**Comment by mwisslead** [comment]
Not sure what you mean by python version but just download the updated master.zip to get the new code. It has been tested with python 3.6 32-bit and python 2.7 32-bit.

**Comment by Act1234** [comment]
You mean to say that once again i need to download  foxpro2python?.   I done the same and installed python27 into the same directory.  After installation, i didn't find python27.dll.  So that from google i downloaded the dll and copied to python27 directory.  
When i ran the test.prg, while executing py_initalize() method, foxpro got closed.

There will be several python 3.6 and python 2.7 for 32 bit exist.  Example: Python 3.6.0a1 - 2016-05-17.

So can you please tell me which python version i want to install

**Comment by mwisslead** [comment]
You only need to redownload foxpro2python if you don't have the commits I added earlier today.

As for python version 3.6.6 and 2.7.13 has been tested working but anything 2.7 or 3.3+ should work. Tests.prg now takes a parameter to specify the python directory. This should be the directory with the exe, dll and other supporting files/folders in it.

As an example, download the latest master.zip ([https://github.com/mwisslead/foxpro2python/archive/master.zip](url)) if you need it then download python 3.6.8 ([https://www.python.org/ftp/python/3.6.8/python-3.6.8.exe](url)) and install it on your machine. In foxpro go to the folder with foxpro2python in it and run the command "do tests.prg with 'C:\path\to\pythondirectory'"

**Comment by Act1234** [comment]
Hi

Great.  It is working.  I am having one more clarification.

As i already informed you that i created a module.  When i compile the module using python command it is giving "Invalid Syntax" error.  The details are as follows.

from sklearn.linear_model import LinearRegression
regx = LinearRegression()

When "python -m py_compile Reg_sample.py" givien in python, it is showing 
"Reg_sample.py", line 16
    regx = LinearRegression()
       ^
Syntax Error: invalid syntax

If i run individual statement in IDE, it is working fine.  When i make  as a module and compile it is giving error.  Can you please help me to sort out this.

**Comment by mwisslead** [comment]
Great to hear. I will go ahead and close the issue.

Though not relevant to foxpro2python, the Syntax Error must be a legitimate python syntax error but the lines you show do not have a syntax error. My guess is you are missing a parenthesis on the line just before where it is showing an error.
